# Week 1: August 26, 2022

## General Overview

- Syllabus
- Food sign up sheet
- GAISE:    
Write for a few minutes - which recommendation do you think is most important to the class you're working on this semester and why?
  - Think/pair/share
  - Whole class discussion

- Microteaching questions
  - Share in pairs
  - Pick one to share with group
  - Give feedback
  - Pair revise chosen question and post in discussion board

## Reminders
- Contract
- Get used to getting assignments after class

## GAISE
- Incorporating real data & data collection
- Key concepts over procedures
- Group activities
- Literacy over calculation/procedures
- Computations of probability
- Activities - student engagement and gauging understanding
- Conceptual understanding

## Microteaching Questions


## Next week
- Write: shared understanding that students should have about measures of center

- fundamental concepts/learning objectives related to measures of center
- How do these questions address these fundamental concepts?

- Rubrics for mean/median questions

- Collect contracts

HW: write question to assess students' understanding of variability


\cleardoublepage

